FROM php:7.3-fpm
RUN pecl install xdebug \
        && docker-php-ext-enable xdebug  \
        && echo "xdebug.remote_enable=On" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini \
        && echo "xdebug.remote_host=10.0.1.11" >> /usr/local/etc/php/conf.d/xdebug.ini
RUN apt-get update; \
    apt-get install -y libpng-dev procps; \
    docker-php-ext-install gd \
    pdo \
    pdo_mysql \
    mbstring \
    sockets \
    json

EXPOSE 80