version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - ${NGINX_PORT_HOST}:${NGINX_PORT_CONTAINER}
    volumes:
      - ${APP_PATH_HOST_BACK}:${APP_PATH_CONTAINER_BACK}
      - ${SITES_ENABLED_HOST_BACK}:${SITES_ENABLED_CONTAINER_BACK}
    depends_on:
      - php

  php:
    build:
      context: ${BACKEND_FOLDER}
      dockerfile: Dockerfile_dev
    image: fpm_7.2:latest
    volumes:
      - ${APP_PATH_HOST_BACK}:${APP_PATH_CONTAINER_BACK}
      - ./php/crontab:/etc/crontab
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./backend/supervisord.conf:/etc/supervisor/supervisord.conf
    working_dir: ${APP_PATH_CONTAINER_BACK}

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: devpass
    volumes:
      - ../db_volume:/var/lib/mysql
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    depends_on:
      - php

  composer:
    image: composer:1.7.2
    volumes:
          - ${APP_PATH_HOST_BACK}:${APP_PATH_CONTAINER_BACK}
    working_dir: ${APP_PATH_CONTAINER_BACK}
    command: composer update --ignore-platform-reqs --no-scripts

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
#    ports:
#      - 9200:9200
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

#  logstash:
#    build:
#      context: ${LOGSTASH_FOLDER}
#      dockerfile: Dockerfile
#    image: logstash:latest
#    depends_on:
#      - elasticsearch
#    ports:
#      - 5044:5044/udp
#    volumes:
#      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
#      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    #command: bin/logstash -f logstash.yml

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.1.1
#    depends_on:
#      - elasticsearch
#    volumes:
#      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#    ports:
#      - 5601:5601

#  inex_front:
#    image: node:8-alpine
#    ports:
#          - ${REACT_PORT_HOST}:${REACT_PORT_CONTAINER}
#    volumes:
#      - ${APP_PATH_HOST_FRONT}:${APP_PATH_CONTAINER_FRONT}
#    working_dir: ${APP_PATH_CONTAINER_FRONT}
#    command: [sh, -c, "npm install && npm start"]
